services:
  - docker

dist: trusty

jobs:
  include:
    - stage: "All"
      name: "Tests"
      install: docker pull holochain/app-spec-rust:master
      script:
        - . docker/run-update && . docker/run-test-ci
